name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: c-hive/gha-yarn-cache@v2
          # with:
        # directory: server # Optional, speficy the folder of yarn.lock if not in the root directory

      - name: Install JS dependencies
        run: yarn install
      - name: Test
        run: yarn test